events {}

http {
  server {
    listen 80;

    location /cogniva/ {
      proxy_pass http://cogniva-backend:8000/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /itsquizz/ {
      proxy_pass http://itsquizz-backend:5000/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
      return 200 "NGINX GATEWAY OK\n";
    }
  }
}
